server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userreg
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
   
  application:
    name: userlog
logging:
  level:
    root: INFO
    com.yourpackage.userservice: DEBUG

# Enable CORS (optional for REST APIs)
cors:
  allowed-origins: "*"
  allowed-methods: "*"

# Custom password encoding config (if needed in service layer)
security:
  encoding-strength: 10

# Optional: Set timezone
