spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

razorpay:
  key_id: rzp_test_BPlNLy2HqsckP6
  key_secret: EZlluVjL7SAtadTr2uON6eRd
server:
  port: 8082



logging:
  level:
    root: INFO
    com.exa.service: DEBUG

# Enable CORS (optional for REST APIs)
cors:
  allowed-origins: "*"
  allowed-methods: "*"